import { DeleteOutlined, PlusOutlined, SaveOutlined } from '@ant-design/icons'
import { Button, Card, Empty, Input, List, Modal, Space, Tag, Typography, message } from 'antd'
import { useEffect, useMemo, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { createAtelierCanvas, createAtelierPrompt, deleteAtelierCanvas, getAtelierCanvas, listAtelierCanvases, listAtelierPrompts, updateAtelierCanvas, type AtelierCanvas, type AtelierPrompt } from '../../api/atelier'
import { createAsset } from '../../api/assets'
import { uploadFileToOss } from '../../utils/oss-upload'
import { ImageNode } from './ImageNode'
import { getLocalImage, putLocalImage, transformLocalImage } from './local-image-store'
import { useAuth } from '../../stores/auth'

type CanvasNode = { id: string; text: string; x: number; y: number; storageKey?: string; name?: string; prompt?: string }
type CanvasDocument = { nodes: CanvasNode[]; viewport?: { x: number; y: number; k: number } }
const emptyDocument: CanvasDocument = { nodes: [], viewport: { x: 0, y: 0, k: 1 } }

const normalizeDocument = (value: Record<string, unknown> | undefined): CanvasDocument => {
  const nodes: CanvasNode[] = Array.isArray(value?.nodes) ? value.nodes.filter((node): node is CanvasNode => Boolean(node && typeof node === 'object' && typeof (node as CanvasNode).id === 'string')).map((node) => ({ id: node.id, text: node.text || '图片节点', x: Number(node.x) || 80, y: Number(node.y) || 80, storageKey: node.storageKey, name: node.name, prompt: node.prompt })) : []
  return { nodes: nodes.map((node) => ({ ...node, storageKey: node.storageKey, name: node.name, prompt: node.prompt })), viewport: { x: 0, y: 0, k: 1 } }
}

export const InfiniteAtelierPage = () => {
  const { state } = useAuth(); const navigate = useNavigate(); const { '*': wildcard } = useParams(); const canvasId = wildcard ? Number(wildcard.split('/').filter(Boolean).pop()) : null
  const [canvases, setCanvases] = useState<AtelierCanvas[]>([]); const [canvas, setCanvas] = useState<AtelierCanvas | null>(null); const [document, setDocument] = useState<CanvasDocument>(emptyDocument); const [prompts, setPrompts] = useState<AtelierPrompt[]>([]); const [promptQuery, setPromptQuery] = useState(''); const [promptModal, setPromptModal] = useState(false); const [promptTitle, setPromptTitle] = useState(''); const [promptContent, setPromptContent] = useState(''); const [saving, setSaving] = useState(false); const [uploadingAsset, setUploadingAsset] = useState(false); const [localUrls, setLocalUrls] = useState<Record<string, string>>({})
  const projectId = state.activeProjectId
  const load = async () => { if (!projectId) return; const [items, promptItems] = await Promise.all([listAtelierCanvases(), listAtelierPrompts(promptQuery)]); setCanvases(items); setPrompts(promptItems); if (canvasId) { const current = await getAtelierCanvas(canvasId); setCanvas(current); setDocument(normalizeDocument(current.documentJson)) } }
  useEffect(() => { void load().catch((error) => message.error(error instanceof Error ? error.message : '加载无限画布失败')) }, [projectId, canvasId, promptQuery])
  useEffect(() => { let disposed = false; const created: string[] = []; void Promise.all(document.nodes.map(async (node) => { if (!node.storageKey) return; const blob = await getLocalImage(node.storageKey); if (!blob || disposed) return; const url = URL.createObjectURL(blob); created.push(url); setLocalUrls((current) => ({ ...current, [node.id]: url })) })); return () => { disposed = true; created.forEach(URL.revokeObjectURL) } }, [document.nodes])
  const openCanvas = (item: AtelierCanvas) => navigate(`/infinite-atelier/${item.id}`)
  const createCanvas = async () => { try { const created = await createAtelierCanvas({ title: `未命名画布 ${canvases.length + 1}`, documentJson: emptyDocument }); setCanvases((items) => [created, ...items]); openCanvas(created) } catch (error) { message.error(error instanceof Error ? error.message : '创建画布失败') } }
  const save = async () => { if (!canvas) return; setSaving(true); try { const updated = await updateAtelierCanvas(canvas.id, { version: canvas.version, documentJson: document }); setCanvas(updated); setCanvases((items) => items.map((item) => item.id === updated.id ? updated : item)); message.success('画布已保存') } catch (error) { message.error(error instanceof Error ? error.message : '保存画布失败') } finally { setSaving(false) } }
  const remove = async (item: AtelierCanvas) => { Modal.confirm({ title: '删除画布？', content: '删除后仅创建者可以再次操作，项目管理员也不能接管。', okType: 'danger', onOk: async () => { await deleteAtelierCanvas(item.id); setCanvases((items) => items.filter((candidate) => candidate.id !== item.id)); if (canvas?.id === item.id) { setCanvas(null); navigate('/infinite-atelier') } } }) }
  const importLocalImage = async (file: File) => { const storageKey = await putLocalImage(file); setDocument((current) => ({ ...current, nodes: [...current.nodes, { id: crypto.randomUUID(), text: file.name, name: file.name.replace(/\.[^.]+$/, ''), storageKey, prompt: selectedPrompt, x: 120 + current.nodes.length * 24, y: 100 + current.nodes.length * 24 }] })) }
  const replaceNodeImage = async (node: CanvasNode, operation: 'crop' | 'upscale' | 'mask') => { if (!node.storageKey) return; const storageKey = await transformLocalImage(node.storageKey, operation); setDocument((current) => ({ ...current, nodes: current.nodes.map((item) => item.id === node.id ? { ...item, storageKey } : item) })) }
  const splitNodeImage = async (node: CanvasNode) => { if (!node.storageKey) return; const [left, right] = await Promise.all([transformLocalImage(node.storageKey, 'split-left'), transformLocalImage(node.storageKey, 'split-right')]); setDocument((current) => ({ ...current, nodes: current.nodes.flatMap((item) => item.id !== node.id ? [item] : [{ ...item, storageKey: left, name: `${item.name ?? '图片'}-左` }, { ...item, id: crypto.randomUUID(), storageKey: right, name: `${item.name ?? '图片'}-右`, x: item.x + 210 }]) })) }
  const addToProjectAssets = async (file: File) => { if (!projectId || !canvas) return; setUploadingAsset(true); try { const { ossKey } = await uploadFileToOss(file); await createAsset({ name: file.name.replace(/\.[^.]+$/, ''), assetType: 'Image', categoryId: null, syncMode: 'disabled', ossKey, tags: ['infinite-atelier'], promptContent: selectedPrompt || null }); message.success('素材已上传并加入项目资产库') } catch (error) { message.error(error instanceof Error ? error.message : '加入资产库失败') } finally { setUploadingAsset(false) } }
  const savePrompt = async () => { try { const created = await createAtelierPrompt({ title: promptTitle, content: promptContent }); setPrompts((items) => [created, ...items]); setPromptModal(false); setPromptTitle(''); setPromptContent('') } catch (error) { message.error(error instanceof Error ? error.message : '保存提示词失败') } }
  const selectedPrompt = useMemo(() => prompts[0]?.content ?? '', [prompts])
  return <div style={{ display: 'grid', gap: 16 }}>
    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}><div><Typography.Title level={2} style={{ margin: 0 }}>无限画布</Typography.Title><Typography.Text type="secondary">当前项目：{state.projects.find((project) => project.id === projectId)?.name ?? '未选择'}</Typography.Text></div><Space><Button icon={<PlusOutlined />} type="primary" onClick={() => void createCanvas()}>新建画布</Button>{canvas ? <Button icon={<SaveOutlined />} loading={saving} onClick={() => void save()}>保存</Button> : null}</Space></div>
    {!canvas ? <Card><List dataSource={canvases} locale={{ emptyText: <Empty description="还没有画布" /> }} renderItem={(item) => <List.Item actions={[<Button key="open" type="link" onClick={() => openCanvas(item)}>打开</Button>, <Button key="delete" danger type="link" icon={<DeleteOutlined />} onClick={() => void remove(item)}>删除</Button>]}><List.Item.Meta title={item.title} description={`版本 ${item.version} · ${new Date(item.updatedAt).toLocaleString()}`} /></List.Item>} /></Card> : <div style={{ display: 'grid', gridTemplateColumns: 'minmax(0, 1fr) 320px', gap: 16 }}><Card title={canvas.title} extra={<Space><label style={{ display: 'inline-block' }}><input type="file" accept="image/*" hidden onChange={(event) => { const file = event.target.files?.[0]; if (file) void importLocalImage(file); event.currentTarget.value = '' }} /><Button>导入图片</Button></label><label style={{ display: 'inline-block' }}><input type="file" accept="image/*" hidden disabled={uploadingAsset} onChange={(event) => { const file = event.target.files?.[0]; if (file) void addToProjectAssets(file); event.currentTarget.value = '' }} /><Button loading={uploadingAsset}>上传并加入资产库</Button></label><Button onClick={() => navigate('/infinite-atelier')}>返回列表</Button></Space>}><div style={{ position: 'relative', minHeight: 560, overflow: 'hidden', borderRadius: 12, backgroundColor: '#f6f4ef', backgroundImage: 'linear-gradient(#e4dfd2 1px, transparent 1px), linear-gradient(90deg, #e4dfd2 1px, transparent 1px)', backgroundSize: '32px 32px', display: 'grid', gridTemplateColumns: 'repeat(auto-fill,minmax(180px,1fr))', alignContent: 'start', gap: 16, padding: 16 }}>{document.nodes.map((node) => <div key={node.id}><ImageNode name={node.name ?? node.text} prompt={node.prompt} url={localUrls[node.id]} onCrop={() => void replaceNodeImage(node, 'crop')} onSplit={() => void splitNodeImage(node)} onUpscale={() => void replaceNodeImage(node, 'upscale')} onMask={() => void replaceNodeImage(node, 'mask')} /></div>)}{document.nodes.length === 0 ? <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="画布为空，导入图片开始创作" style={{ paddingTop: 180, gridColumn: '1/-1' }} /> : null}</div></Card><Card title="项目提示词" extra={<Button type="link" onClick={() => setPromptModal(true)}>新增</Button>}><Input allowClear value={promptQuery} onChange={(event) => setPromptQuery(event.target.value)} placeholder="搜索提示词" /><List size="small" dataSource={prompts} renderItem={(prompt) => <List.Item actions={[<Button key="use" type="link" onClick={() => setDocument((current) => ({ ...current, nodes: current.nodes.map((node, index) => index === 0 ? { ...node, text: prompt.content, prompt: prompt.content } : node) }))}>使用</Button>]}><List.Item.Meta title={<span>{prompt.title} <Tag>{prompt.version}</Tag></span>} description={prompt.content} /></List.Item>} />{selectedPrompt ? <Typography.Paragraph type="secondary">提示词正文与资产名称分开保存，资产名称不会作为图片生成提示词发送。</Typography.Paragraph> : null}</Card></div>}
    <Modal open={promptModal} title="新增项目提示词" onCancel={() => setPromptModal(false)} onOk={() => void savePrompt()}><Input style={{ marginBottom: 12 }} value={promptTitle} onChange={(event) => setPromptTitle(event.target.value)} placeholder="标题" /><Input.TextArea rows={6} value={promptContent} onChange={(event) => setPromptContent(event.target.value)} placeholder="提示词正文" /></Modal>
  </div>
}
