import { sql, type Kysely } from 'kysely'

import type { Database } from '../kysely'

export const up = async (db: Kysely<Database>): Promise<void> => {
  const promptColumn = await sql<{ exists: boolean }>`select exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'assets' and column_name = 'prompt_content')`.execute(db)
  await sql`create table if not exists atelier_migration_metadata (key varchar(200) primary key, value varchar(50) not null)`.execute(db)
  await sql`insert into atelier_migration_metadata (key, value) values ('assets.prompt_content', ${promptColumn.rows[0]?.exists ? 'preexisting' : 'created'}) on conflict (key) do nothing`.execute(db)
  await sql`alter table assets add column if not exists prompt_content text`.execute(db)

  await db.schema.createTable('atelier_canvases').ifNotExists()
    .addColumn('id', 'bigserial', (c) => c.primaryKey())
    .addColumn('project_id', 'bigint', (c) => c.notNull().references('projects.id').onDelete('restrict'))
    .addColumn('created_by_user_id', 'bigint', (c) => c.notNull().references('users.id').onDelete('restrict'))
    .addColumn('title', 'varchar(300)', (c) => c.notNull())
    .addColumn('document_json', 'jsonb', (c) => c.notNull().defaultTo(sql`'{}'::jsonb`))
    .addColumn('version', 'integer', (c) => c.notNull().defaultTo(1))
    .addColumn('status', 'varchar(16)', (c) => c.notNull().defaultTo('active'))
    .addColumn('client_stable_id', 'varchar(200)')
    .addColumn('created_at', 'timestamptz', (c) => c.notNull().defaultTo(sql`now()`))
    .addColumn('updated_at', 'timestamptz', (c) => c.notNull().defaultTo(sql`now()`))
    .addColumn('deleted_at', 'timestamptz')
    .execute()
  await db.schema.createIndex('idx_atelier_canvases_owner').ifNotExists().on('atelier_canvases').columns(['project_id', 'created_by_user_id', 'updated_at']).execute()

  await db.schema.createTable('atelier_prompts').ifNotExists()
    .addColumn('id', 'bigserial', (c) => c.primaryKey())
    .addColumn('project_id', 'bigint', (c) => c.notNull().references('projects.id').onDelete('restrict'))
    .addColumn('title', 'varchar(300)', (c) => c.notNull())
    .addColumn('tags', 'jsonb', (c) => c.notNull().defaultTo(sql`'[]'::jsonb`))
    .addColumn('current_version', 'integer', (c) => c.notNull().defaultTo(1))
    .addColumn('created_by_user_id', 'bigint', (c) => c.notNull().references('users.id').onDelete('restrict'))
    .addColumn('updated_by_user_id', 'bigint', (c) => c.notNull().references('users.id').onDelete('restrict'))
    .addColumn('status', 'varchar(16)', (c) => c.notNull().defaultTo('active'))
    .addColumn('client_stable_id', 'varchar(200)')
    .addColumn('created_at', 'timestamptz', (c) => c.notNull().defaultTo(sql`now()`))
    .addColumn('updated_at', 'timestamptz', (c) => c.notNull().defaultTo(sql`now()`))
    .addColumn('deleted_at', 'timestamptz')
    .execute()
  await db.schema.createIndex('idx_atelier_prompts_project_status').ifNotExists().on('atelier_prompts').columns(['project_id', 'status', 'updated_at']).execute()
  await db.schema.createTable('atelier_prompt_versions').ifNotExists()
    .addColumn('project_id', 'bigint', (c) => c.notNull().references('projects.id').onDelete('restrict'))
    .addColumn('prompt_id', 'bigint', (c) => c.notNull().references('atelier_prompts.id').onDelete('restrict'))
    .addColumn('version', 'integer', (c) => c.notNull())
    .addColumn('content', 'text', (c) => c.notNull())
    .addColumn('updated_by_user_id', 'bigint', (c) => c.notNull().references('users.id').onDelete('restrict'))
    .addColumn('created_at', 'timestamptz', (c) => c.notNull().defaultTo(sql`now()`))
    .addPrimaryKeyConstraint('pk_atelier_prompt_versions', ['project_id', 'prompt_id', 'version'])
    .execute()

  await db.schema.createTable('atelier_storage_objects').ifNotExists()
    .addColumn('id', 'bigserial', (c) => c.primaryKey())
    .addColumn('project_id', 'bigint', (c) => c.notNull().references('projects.id').onDelete('restrict'))
    .addColumn('created_by_user_id', 'bigint', (c) => c.notNull().references('users.id').onDelete('restrict'))
    .addColumn('object_key', 'varchar(1000)', (c) => c.notNull())
    .addColumn('category', 'varchar(32)', (c) => c.notNull())
    .addColumn('content_type', 'varchar(255)', (c) => c.notNull())
    .addColumn('bytes', 'bigint', (c) => c.notNull().defaultTo(0))
    .addColumn('etag', 'varchar(255)')
    .addColumn('metadata', 'jsonb', (c) => c.notNull().defaultTo(sql`'{}'::jsonb`))
    .addColumn('state', 'varchar(32)', (c) => c.notNull().defaultTo('active'))
    .addColumn('created_at', 'timestamptz', (c) => c.notNull().defaultTo(sql`now()`))
    .addColumn('updated_at', 'timestamptz', (c) => c.notNull().defaultTo(sql`now()`))
    .addColumn('deleted_at', 'timestamptz')
    .execute()
  await db.schema.createIndex('uq_atelier_storage_project_key').ifNotExists().on('atelier_storage_objects').columns(['project_id', 'object_key']).unique().execute()
  await db.schema.createTable('atelier_canvas_object_links').ifNotExists()
    .addColumn('project_id', 'bigint', (c) => c.notNull().references('projects.id').onDelete('restrict'))
    .addColumn('canvas_id', 'bigint', (c) => c.notNull().references('atelier_canvases.id').onDelete('restrict'))
    .addColumn('object_id', 'bigint', (c) => c.notNull().references('atelier_storage_objects.id').onDelete('restrict'))
    .addColumn('role', 'varchar(50)', (c) => c.notNull())
    .addColumn('sequence_no', 'integer', (c) => c.notNull().defaultTo(0))
    .addColumn('created_at', 'timestamptz', (c) => c.notNull().defaultTo(sql`now()`))
    .addPrimaryKeyConstraint('pk_atelier_canvas_object_links', ['project_id', 'canvas_id', 'object_id', 'role'])
    .execute()

  await db.schema.createTable('atelier_generation_tasks').ifNotExists()
    .addColumn('id', 'bigserial', (c) => c.primaryKey())
    .addColumn('project_id', 'bigint', (c) => c.notNull().references('projects.id').onDelete('restrict'))
    .addColumn('created_by_user_id', 'bigint', (c) => c.notNull().references('users.id').onDelete('restrict'))
    .addColumn('canvas_id', 'bigint')
    .addColumn('canvas_version', 'integer')
    .addColumn('prompt_id', 'bigint')
    .addColumn('prompt_version', 'integer')
    .addColumn('operation', 'varchar(100)', (c) => c.notNull())
    .addColumn('media_type', 'varchar(16)', (c) => c.notNull())
    .addColumn('channel_key', 'varchar(128)')
    .addColumn('model', 'varchar(255)', (c) => c.notNull())
    .addColumn('idempotency_key', 'varchar(255)', (c) => c.notNull())
    .addColumn('request_json', 'jsonb', (c) => c.notNull().defaultTo(sql`'{}'::jsonb`))
    .addColumn('status', 'varchar(32)', (c) => c.notNull().defaultTo('pending'))
    .addColumn('progress_percent', 'integer', (c) => c.notNull().defaultTo(0))
    .addColumn('provider_task_id', 'varchar(255)')
    .addColumn('error_code', 'varchar(128)')
    .addColumn('error_message', 'text')
    .addColumn('created_at', 'timestamptz', (c) => c.notNull().defaultTo(sql`now()`))
    .addColumn('updated_at', 'timestamptz', (c) => c.notNull().defaultTo(sql`now()`))
    .execute()
  await db.schema.createIndex('uq_atelier_generation_idempotency').ifNotExists().on('atelier_generation_tasks').columns(['project_id', 'created_by_user_id', 'operation', 'idempotency_key']).unique().execute()
  await db.schema.createTable('atelier_generation_outputs').ifNotExists()
    .addColumn('id', 'bigserial', (c) => c.primaryKey())
    .addColumn('project_id', 'bigint', (c) => c.notNull().references('projects.id').onDelete('restrict'))
    .addColumn('task_id', 'bigint', (c) => c.notNull().references('atelier_generation_tasks.id').onDelete('restrict'))
    .addColumn('sequence_no', 'integer', (c) => c.notNull().defaultTo(0))
    .addColumn('object_id', 'bigint')
    .addColumn('content_type', 'varchar(255)', (c) => c.notNull())
    .addColumn('bytes', 'bigint')
    .addColumn('status', 'varchar(32)', (c) => c.notNull().defaultTo('pending'))
    .addColumn('created_at', 'timestamptz', (c) => c.notNull().defaultTo(sql`now()`))
    .execute()
}

export const down = async (db: Kysely<Database>): Promise<void> => {
  await db.schema.dropTable('atelier_generation_outputs').ifExists().execute()
  await db.schema.dropIndex('uq_atelier_generation_idempotency').ifExists().execute()
  await db.schema.dropTable('atelier_generation_tasks').ifExists().execute()
  await db.schema.dropTable('atelier_canvas_object_links').ifExists().execute()
  await db.schema.dropIndex('uq_atelier_storage_project_key').ifExists().execute()
  await db.schema.dropTable('atelier_storage_objects').ifExists().execute()
  await db.schema.dropTable('atelier_prompt_versions').ifExists().execute()
  await db.schema.dropIndex('idx_atelier_prompts_project_status').ifExists().execute()
  await db.schema.dropTable('atelier_prompts').ifExists().execute()
  await db.schema.dropIndex('idx_atelier_canvases_owner').ifExists().execute()
  await db.schema.dropTable('atelier_canvases').ifExists().execute()
  const marker = await sql<{ value: string }>`select value from atelier_migration_metadata where key = 'assets.prompt_content'`.execute(db)
  if (marker.rows[0]?.value === 'created') await sql`alter table assets drop column if exists prompt_content`.execute(db)
  await sql`drop table if exists atelier_migration_metadata`.execute(db)
}
